export type StateCode =
  | 'RESERVATION_REQUESTED'
  | 'PHOTOGRAPHER_CHECKING'
  | 'PAYMENT_REQUESTED'
  | 'PAYMENT_COMPLETED'
  | 'RESERVATION_CONFIRMED'
  | 'RESERVATION_REFUSED'
  | 'RESERVATION_CANCELED'
  | 'SHOOT_COMPLETED';

export const STATE_CODES = {
  RESERVATION_REQUESTED: 'RESERVATION_REQUESTED',
  PHOTOGRAPHER_CHECKING: 'PHOTOGRAPHER_CHECKING',
  PAYMENT_REQUESTED: 'PAYMENT_REQUESTED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
  RESERVATION_REFUSED: 'RESERVATION_REFUSED',
  RESERVATION_CANCELED: 'RESERVATION_CANCELED',
  SHOOT_COMPLETED: 'SHOOT_COMPLETED',
} as const satisfies Record<string, StateCode>;
