export const RESERVATION_TAB = {
  PHOTOGRAPHER_REQUESTED: 'PHOTOGRAPHER_REQUESTED',
  PHOTOGRAPHER_ADJUSTING: 'PHOTOGRAPHER_ADJUSTING',
  PHOTOGRAPHER_CONFIRMED: 'PHOTOGRAPHER_CONFIRMED',
  PHOTOGRAPHER_DONE: 'PHOTOGRAPHER_DONE',
} as const;

export const RESERVATION_TAB_MAP: Record<ReservationTab, string> = {
  PHOTOGRAPHER_REQUESTED: '예약 요청',
  PHOTOGRAPHER_ADJUSTING: '조율 중',
  PHOTOGRAPHER_CONFIRMED: '예약 확정',
  PHOTOGRAPHER_DONE: '촬영 완료',
} as const;

export type ReservationTab = keyof typeof RESERVATION_TAB;

