export type StateCode =
  | 'RESERVATION_REQUESTED' // 예약 요청
  | 'PHOTOGRAPHER_CHECKING' // 작가 확인 중
  | 'PAYMENT_REQUESTED' // 결제 요청
  | 'PAYMENT_COMPLETED' // 결제 완료
  | 'RESERVATION_CONFIRMED' // 예약 확정
  | 'RESERVATION_REFUSED' // 예약 거절
  | 'RESERVATION_CANCELED' // 예약 취소
  | 'SHOOT_COMPLETED'; // 촬영 완료

export const STATE_CODES = {
  RESERVATION_REQUESTED: 'RESERVATION_REQUESTED',
  PHOTOGRAPHER_CHECKING: 'PHOTOGRAPHER_CHECKING',
  PAYMENT_REQUESTED: 'PAYMENT_REQUESTED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
  RESERVATION_REFUSED: 'RESERVATION_REFUSED',
  RESERVATION_CANCELED: 'RESERVATION_CANCELED',
  SHOOT_COMPLETED: 'SHOOT_COMPLETED',
} as const satisfies Record<string, StateCode>;
