export enum SECTION_TAB {
  PORTFOLIO = 'PORTFOLIO',
  PRODUCT = 'PRODUCT',
  REVIEW = 'REVIEW',
  PRODUCT_INFO = 'PRODUCT_INFO',

  REQUEST = 'REQUEST',
  COORDINATING = 'COORDINATING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
}

export const SECTION_TAB_LABEL: Record<SECTION_TAB, string> = {
  [SECTION_TAB.PORTFOLIO]: '포트폴리오',
  [SECTION_TAB.PRODUCT]: '상품',
  [SECTION_TAB.PRODUCT_INFO]: '상품 안내',
  [SECTION_TAB.REVIEW]: '리뷰',

  [SECTION_TAB.REQUEST]: '예약 요청',
  [SECTION_TAB.COORDINATING]: '조율 중',
  [SECTION_TAB.CONFIRMED]: '예약 확정',
  [SECTION_TAB.COMPLETED]: '촬영 완료',
};

export const SECTION_TAB_PRESET = {
  CLIENT_TAB: [SECTION_TAB.PORTFOLIO, SECTION_TAB.PRODUCT],

  DETAIL_TAB: [SECTION_TAB.PRODUCT_INFO, SECTION_TAB.PORTFOLIO, SECTION_TAB.REVIEW],

  AUTHOR_RESERVATION: [
    SECTION_TAB.REQUEST,
    SECTION_TAB.COORDINATING,
    SECTION_TAB.CONFIRMED,
    SECTION_TAB.COMPLETED,
  ],
} as const;

export function getSectionTabLabel(tab: SECTION_TAB, options?: { reviewCount?: number }) {
  if (tab === SECTION_TAB.REVIEW && options?.reviewCount !== undefined) {
    return `리뷰 (${options.reviewCount})`;
  }

  return SECTION_TAB_LABEL[tab];
}
