export const PHOTOGRAPHER_QUERY_KEY = {
    RESERVATION: ['reservation'],
    RESERVATION_LISTS:() => [...PHOTOGRAPHER_QUERY_KEY.RESERVATION, 'list'],
    RESERVATION_LIST:(tab: string)=> [...PHOTOGRAPHER_QUERY_KEY.RESERVATION_LISTS(), tab],
} as const;