export const PHOTOGRAPHER_QUERY_KEY = {
    RESERVATION: ['reservation'],
    RESERVATION_LISTS:() => [...PHOTOGRAPHER_QUERY_KEY.RESERVATION, 'list'],
    RESERVATION_LIST:(tab: string)=> [...PHOTOGRAPHER_QUERY_KEY.RESERVATION_LISTS(), tab],
    RESERVATION_DETAILS:() => [...PHOTOGRAPHER_QUERY_KEY.RESERVATION, 'details'],
    RESERVATION_DETAIL:(id: number)=> [...PHOTOGRAPHER_QUERY_KEY.RESERVATION_DETAILS(), id],
    PRODUCT_PRICE:(id: number)=> [...PHOTOGRAPHER_QUERY_KEY.RESERVATION, 'price', id],
    REVIEW_DETAILS:() => [...PHOTOGRAPHER_QUERY_KEY.RESERVATION, 'review'],
    REVIEW_DETAIL:(reviewId: number)=> [...PHOTOGRAPHER_QUERY_KEY.REVIEW_DETAILS(), reviewId],
} as const;