export const USER_QUERY_KEY = {
  RESERVATION: ['reservation'],
  RESERVATION_CLIENT_VIEW: () => [...USER_QUERY_KEY.RESERVATION, 'CLIENT_VIEW'],
  RESERVATION_CLIENT_DONE: () => [...USER_QUERY_KEY.RESERVATION, 'CLIENT_DONE'],
} as const;
