// TODO: 서버 enum 확정되면 변경
export type StateCode =
  | 'RESERVATION_REQUESTED'
  | 'AUTHOR_CONFIRMING'
  | 'PAYMENT_REQUESTED'
  | 'PAYMENT_COMPLETED'
  | 'RESERVATION_COMPLETED'
  | 'RESERVATION_CANCELLED'
  | 'SHOOT_COMPLETED';